- name: Configure Servers as github Runners
  hosts: myrunners
#  become: yes
  tasks:
    - name: copy ssh key for test purposes
      command: ssh-import-id-gh MichaelKora
    - name: Create a folder
      command: |
        mkdir -p actions-runner
        pwd
        ls -al
    - name: Download the latest runner package
      command: |
      curl -o actions-runner-linux-x64-2.287.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.287.1/actions-runner-linux-x64-2.287.1.tar.gz
      ls -al
    - name: Validate the hash
      command: echo "325b89bdc1c67264ec6f4515afda4534f14a6477d9ba241da19c43f9bed2f5a6  actions-runner-linux-x64-2.288.1.tar.gz" | shasum -a 256 -c
    - name: Extract the installer
      command: tar xzf ./actions-runner-linux-x64-2.287.1.tar.gz
    - name: pwd
      command: pwd
    - name: ls
      command: ls -al 
    
- name: Activate and test the first runner
  hosts: runner-1
#  become: yes
  tasks:
    - name: Configure and start the runner1
      command: |
        ./config.sh --url https://github.com/MichaelKora/self-hosted-runners --token ATILRBWKGIJDB7ZGFXD56N3CEXW42 --labels linux,x64,runner1 --name myrunner1 --unattended --ephemeral

- name: Activate and test the  second runner
  hosts: runner-2
#  become: yes
  tasks:
    - name: Configure and start the runner2
      command: |
        ./config.sh --url https://github.com/MichaelKora/self-hosted-runners --token ATILRBWKGIJDB7ZGFXD56N3CEXW42 --labels linux,x64,runner2 --name myrunner2 --unattended --ephemeral
  
- name: Activate and test the  the runner3
  hosts: runner-3
#  become: yes
  tasks:
    - name: Create a folder
      command: |
        ./config.sh --url https://github.com/MichaelKora/self-hosted-runners --token ATILRBWKGIJDB7ZGFXD56N3CEXW42 --labels linux,x64,runner3 --name myrunner3 --unattended --ephemeral

- name: Configure with svc.sh
  hosts: myrunners
  become: yes
  become_user: ubuntu
  tasks:
    - name: ./svc.sh install && ./svc.sh start
      command: |
        sudo ./svc.sh install
        sudo ./svc.sh start
