name: destroy created instances

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["self hosted runner"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      OS_TENANT_ID: ${{ secrets.OS_TENANT_ID }}
      OS_TENANT_NAME: ${{ secrets.OS_TENANT_NAME }}
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_REGION_NAME: ${{ secrets.OS_REGION_NAME }}
      TF_VAR_ANSIBLE_USER: ${{ secrets.TF_VAR_ANSIBLE_USER }}
      GITHUB_OWNER: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v2
      
      - name: connect to open stack
        shell: bash -l {0}
        run: bash ./openrc.sh ${{ env.OS_TENANT_ID }} ${{ env.OS_TENANT_NAME }}  ${{ env.OS_USERNAME }} ${{ env.OS_PASSWORD }} ${{ env.OS_REGION_NAME }}

      - name: set up the env variables
        shell: bash -l {0}
        run: bash ./set_env.sh ${{ env.OS_TENANT_ID }} ${{ env.OS_TENANT_NAME }} ${{ env.OS_USERNAME }} ${{ env.OS_PASSWORD }} ${{ env.GITHUB_OWNER }}

      - name: prepare the rest of the variables
        shell: bash -l {0}
        run: bash ./prep_tf.sh ${{ env.GITHUB_OWNER }}

      - name: delete vms
        shell: bash -l {0}
        run: bash ./destroyVMs.sh